In [1]:
import cv2
import numpy as np
import os

# Draw Polygon, Triangle, Line, Rectangle, Hexagon and print text on image

In [2]:
img_path = r"C:\Users\photos\business-woman-2071342_1920.jpg"

img = cv2.imread(img_path)
img_resize = cv2.resize(img, (1280, 720))

cv2.imshow("Model Image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Draw polyline

In [5]:
img_path = r"C:\Users\photos\business-woman-2071342_1920.jpg"

img = cv2.imread(img_path)
img_resize = cv2.resize(img, (1280, 720))

pts = np.array([[12, 45], [34, 56], [23, 76], [67, 98], [93, 56]])
isClosed = True
color = (34, 65, 2)
thickness = 5

# polylines(img, pts, isClosed, color[, thickness[, lineType[, shift]]]) -> img
cv2.polylines(img_resize, [pts], isClosed, color, thickness)

cv2.imshow("Model Image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Draw Octagon using polyline

In [6]:
img_path = r"C:\Users\photos\business-woman-2071342_1920.jpg"

img = cv2.imread(img_path)
img_resize = cv2.resize(img, (1280, 720))

# pts = np.array([[12, 45], [34, 56], [23, 76], [67, 98], [93, 56]])

pts = np.array([[25, 70],[25, 145],
               [75, 190], [150, 190],
               [200, 145], [200, 70],
               [150, 25], [75, 25]],
              np.int32)
isClosed = True
color = (34, 65, 2)
thickness = 5

# polylines(img, pts, isClosed, color[, thickness[, lineType[, shift]]]) -> img
cv2.polylines(img_resize, [pts], isClosed, color, thickness)

cv2.imshow("Model Image", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Draw line, rectangle, triangle using polylines

In [7]:
img_path = r"C:\Users\photos\business-woman-2071342_1920.jpg"

img = cv2.imread(img_path)
img_resize = cv2.resize(img, (1280, 720))

# pts = np.array([[12, 45], [34, 56], [23, 76], [67, 98], [93, 56]])

rectangle = np.array([[10, 5], [10, 225], [50, 225], [50, 5]], np.int32)
triangle = np.array([[60, 10], [60, 200], [150, 100]], np.int32)

line = np.array([[10,11], [10,11], [50, 225], [50, 225]], np.int32)

print(pts)

isClosed = True
color = (34, 23, 45)
thickness = 2

# polylines(img, pts, isClosed, color[, thickness[, lineType[, shift]]]) -> img
cv2.polylines(img_resize, [line], isClosed, color, thickness)

cv2.imshow("Polyline on Model", img_resize)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 25  70]
 [ 25 145]
 [ 75 190]
 [150 190]
 [200 145]
 [200  70]
 [150  25]
 [ 75  25]]


In [8]:
# RECTANGLE

img_path = r"C:\Users\photos\business-woman-2071342_1920.jpg"

img = cv2.imread(img_path)
img_resize = cv2.resize(img, (1280, 720))

# pts = np.array([[12, 45], [34, 56], [23, 76], [67, 98], [93, 56]])

rectangle = np.array([[10, 5], [10, 225], [50, 225], [50, 5]], np.int32)
triangle = np.array([[60, 10], [60, 200], [150, 100]], np.int32)

line = np.array([[10,11], [10,11], [50, 225], [50, 225]], np.int32)

print(pts)

isClosed = True
color = (34, 23, 45)
thickness = 2

# polylines(img, pts, isClosed, color[, thickness[, lineType[, shift]]]) -> img
cv2.polylines(img_resize, [rectangle], isClosed, color, thickness)

cv2.imshow("Polyline on Model", img_resize)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 25  70]
 [ 25 145]
 [ 75 190]
 [150 190]
 [200 145]
 [200  70]
 [150  25]
 [ 75  25]]


In [9]:
# TRiangle

img_path = r"C:\Users\photos\business-woman-2071342_1920.jpg"

img = cv2.imread(img_path)
img_resize = cv2.resize(img, (1280, 720))

# pts = np.array([[12, 45], [34, 56], [23, 76], [67, 98], [93, 56]])

rectangle = np.array([[10, 5], [10, 225], [50, 225], [50, 5]], np.int32)
triangle = np.array([[60, 10], [60, 200], [150, 100]], np.int32)

line = np.array([[10,11], [50, 225]], np.int32)

print(pts)

isClosed = True   # if we want to not close the traingle then we can put false.
color = (34, 23, 45)
thickness = 2

# polylines(img, pts, isClosed, color[, thickness[, lineType[, shift]]]) -> img
cv2.polylines(img_resize, [triangle], isClosed, color, thickness)

cv2.imshow("Polyline on Model", img_resize)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 25  70]
 [ 25 145]
 [ 75 190]
 [150 190]
 [200 145]
 [200  70]
 [150  25]
 [ 75  25]]


# Draw polylines and print text 

In [12]:
img_path = r"C:\Users\photos\business-woman-2071342_1920.jpg"

img = cv2.imread(img_path)
img_resize = cv2.resize(img, (1280, 720))

# pts = np.array([[12, 45], [34, 56], [23, 76], [67, 98], [93, 56]])

pts = np.array([[25, 70],[25, 145],
               [75, 190], [150, 190],
               [200, 145], [200, 70],
               [150, 25], [75, 25]],
              np.int32)
isClosed = True
color = (34, 65, 2)
thickness = 2

# polylines(img, pts, isClosed, color[, thickness[, lineType[, shift]]]) -> img
cv2.polylines(img_resize, [pts], isClosed, color, thickness)

############# print text

# putText(img, text, org, fontFace, fontScale, color[, thickness[, lineType[, bottomLeftOrigin]]]) -> img
cv2.putText(img_resize, "octagon", (50, 100), cv2.FONT_HERSHEY_SCRIPT_SIMPLEX, 1, (200, 20, 200), 2)

# show image
cv2.imshow("Polyline on Model", img_resize)

cv2.waitKey(0)
cv2.destroyAllWindows()