# How to split image in single channel & merge multiple single channel  

In [1]:
import cv2
import numpy as np

In [3]:
img_path = r"C:\Users\photos\beautiful-1434835_1920.jpg"

img = cv2.imread(img_path)
img = cv2.resize(img, (1280, 720))

cv2.imshow("Model Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Split image using numpy indexing

In [4]:
img

array([[[106,  88,  75],
        [106,  88,  75],
        [106,  88,  75],
        ...,
        [101,  79,  68],
        [101,  79,  67],
        [102,  80,  68]],

       [[106,  87,  74],
        [106,  87,  74],
        [106,  87,  74],
        ...,
        [102,  80,  68],
        [102,  80,  68],
        [103,  81,  69]],

       [[106,  87,  74],
        [106,  87,  74],
        [106,  87,  74],
        ...,
        [102,  80,  68],
        [102,  80,  68],
        [103,  81,  69]],

       ...,

       [[ 90, 139, 219],
        [ 90, 139, 219],
        [ 90, 139, 219],
        ...,
        [  8,  17,  44],
        [  8,  17,  44],
        [  8,  17,  44]],

       [[ 93, 142, 222],
        [ 93, 142, 222],
        [ 92, 141, 221],
        ...,
        [  7,  16,  43],
        [  8,  17,  44],
        [  9,  18,  45]],

       [[ 95, 144, 224],
        [ 93, 142, 222],
        [ 92, 141, 221],
        ...,
        [  8,  17,  44],
        [  9,  18,  45],
        [  8,  17,  44]]

In [5]:
img.shape

(720, 1280, 3)

In [6]:
img[:, :, 0]    # : 1st is for it means all rows, : 2 colon is for it means all columns, b=0, g=1, r=2.

array([[106, 106, 106, ..., 101, 101, 102],
       [106, 106, 106, ..., 102, 102, 103],
       [106, 106, 106, ..., 102, 102, 103],
       ...,
       [ 90,  90,  90, ...,   8,   8,   8],
       [ 93,  93,  92, ...,   7,   8,   9],
       [ 95,  93,  92, ...,   8,   9,   8]], dtype=uint8)

In [7]:
img[:, :, 1] 

array([[ 88,  88,  88, ...,  79,  79,  80],
       [ 87,  87,  87, ...,  80,  80,  81],
       [ 87,  87,  87, ...,  80,  80,  81],
       ...,
       [139, 139, 139, ...,  17,  17,  17],
       [142, 142, 141, ...,  16,  17,  18],
       [144, 142, 141, ...,  17,  18,  17]], dtype=uint8)

In [8]:
img[:, :, 2] 

array([[ 75,  75,  75, ...,  68,  67,  68],
       [ 74,  74,  74, ...,  68,  68,  69],
       [ 74,  74,  74, ...,  68,  68,  69],
       ...,
       [219, 219, 219, ...,  44,  44,  44],
       [222, 222, 221, ...,  43,  44,  45],
       [224, 222, 221, ...,  44,  45,  44]], dtype=uint8)

# split image using cv2.split()

In [9]:
#split(m[, mv]) -> mv
b, g, r = cv2.split(img)

In [10]:
b

array([[106, 106, 106, ..., 101, 101, 102],
       [106, 106, 106, ..., 102, 102, 103],
       [106, 106, 106, ..., 102, 102, 103],
       ...,
       [ 90,  90,  90, ...,   8,   8,   8],
       [ 93,  93,  92, ...,   7,   8,   9],
       [ 95,  93,  92, ...,   8,   9,   8]], dtype=uint8)

In [11]:
b.shape

(720, 1280)

In [13]:
g.shape

(720, 1280)

In [14]:
r.shape

(720, 1280)

# Time calculation to split image

In [16]:
import time

start_time = time.time()

for i in range(100):
    r, g, r = cv2.split(img)
    
end_time = time.time()

print("Total time taken to split 100 images: ", end_time - start_time)

Total time taken to split 100 images:  0.638371467590332


# Total calculation to split numpy indexing 

In [17]:
import time

start_time = time.time()

for i in range(100):
    b = img[:, :, 0]
    g = img[:, :, 1]
    r = img[:, :, 2]
    
end_time = time.time()

print("Total time taken to split 100 images: ", end_time - start_time)  # numpy indexing is fast instead of split image.

Total time taken to split 100 images:  0.0


In [18]:
0.638371467590332 -  0.0

0.638371467590332

# show single channel

In [20]:
## show single channels.

img_path = r"C:\Users\photos\beautiful-1434835_1920.jpg"

img = cv2.imread(img_path)
img = cv2.resize(img, (400, 400))

cv2.imshow("Model Blue Image", img[:, :, 0])

cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
# now we can see chaneel using split function.

In [22]:
img_path = r"C:\Users\photos\beautiful-1434835_1920.jpg"

img = cv2.imread(img_path)
img = cv2.resize(img, (400, 400))

b, g, r = cv2.split(img)

cv2.imshow("Model Blue Image", b)


cv2.waitKey(0)
cv2.destroyAllWindows()

# show multiple channels

In [ ]:
img_path = r"C:\Users\photos\beautiful-1434835_1920.jpg"

img = cv2.imread(img_path)
img = cv2.resize(img, (400, 400))

cv2.imshow("Model Blue Image", img[:, :, 0])
cv2.imshow("Model Green Image", img[:, :, 1])
cv2.imshow("Model Red Image", img[:, :, 2])

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# now we can see multiple channels using split function.

In [23]:
img_path = r"C:\Users\photos\beautiful-1434835_1920.jpg"

img = cv2.imread(img_path)
img = cv2.resize(img, (400, 400))

b, g, r = cv2.split(img)

cv2.imshow("Model Blue Image", b)
cv2.imshow("Model Green Image", g)
cv2.imshow("Model Red Image", r)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Merge image

In [25]:
# merge(mv[, dst]) -> dst
img_merge = cv2.merge([b, g, r])
img_merge

array([[[106,  87,  74],
        [105,  87,  76],
        [105,  87,  78],
        ...,
        [103,  81,  70],
        [103,  81,  69],
        [101,  79,  67]],

       [[105,  87,  74],
        [105,  86,  75],
        [106,  87,  79],
        ...,
        [103,  81,  69],
        [103,  81,  69],
        [102,  80,  68]],

       [[105,  86,  73],
        [106,  86,  75],
        [104,  86,  75],
        ...,
        [103,  81,  70],
        [104,  82,  70],
        [103,  81,  70]],

       ...,

       [[ 93, 142, 222],
        [ 90, 139, 219],
        [ 89, 138, 218],
        ...,
        [ 10,  19,  46],
        [  8,  17,  44],
        [  7,  16,  43]],

       [[ 90, 139, 219],
        [ 90, 139, 219],
        [ 93, 142, 222],
        ...,
        [  9,  18,  45],
        [  7,  16,  43],
        [  8,  17,  44]],

       [[ 93, 142, 222],
        [ 93, 142, 222],
        [ 92, 141, 221],
        ...,
        [  8,  17,  44],
        [  9,  19,  46],
        [  9,  18,  45]]

In [26]:
img_merge.shape

(400, 400, 3)

In [27]:
img_path = r"C:\Users\photos\beautiful-1434835_1920.jpg"

img = cv2.imread(img_path)
img = cv2.resize(img, (400, 400))

b, g, r = cv2.split(img)

img_merge = cv2.merge([b, g, r])

cv2.imshow("Model Blue Image", b)
cv2.imshow("Model Green Image", g)
cv2.imshow("Model Red Image", r)

cv2.imshow("Merge Model  Image", img_merge)

cv2.waitKey(0)
cv2.destroyAllWindows()