# Color Pixels Extraction




# How to detect Road Marking Using Opencv

In [1]:
import cv2
import numpy as np

In [3]:
img_path = r"C:\Users\photos\desert-1845318_1920.jpg"

img = cv2.imread(img_path)
img = cv2.resize(img, (1280, 720))

cv2.imshow("Road Image", img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Convert image in gray scale

In [7]:
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.imshow("Gray Image", gray_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Road margin Detection using Color image

In [6]:
gray_img    ## koi bhi black nd white image ki value 0-255 tkhoti h .. 0 is pure black,   255 = white color.

array([[110, 109, 112, ..., 156, 158, 155],
       [114, 111, 121, ..., 154, 153, 158],
       [129, 120, 112, ..., 158, 159, 155],
       ...,
       [ 65,  53,  47, ...,  64,  72,  74],
       [ 78,  48,  38, ...,  45,  51,  81],
       [ 54,  43,  33, ...,  63,  75,  71]], dtype=uint8)

In [8]:
gray_img_copy = np.copy(gray_img)

gray_img_copy[gray_img_copy[:, :] < 180]=0   # value 180 se km hogi to true vrna false

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.imshow("Gray Image", gray_img_copy)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
gray_img_copy = np.copy(gray_img)

gray_img_copy[gray_img_copy[:, :] < 200]=0

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.imshow("Gray Image", gray_img_copy)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
gray_img_copy[:, :] < 180

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [11]:
gray_img_copy

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [12]:
gray_img_copy[:, 300]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 201, 200, 200, 200, 201, 201, 201, 202, 202, 203,
       203, 203, 203, 204, 204, 204, 204, 204, 203, 204, 205, 205, 204,
       206, 206, 206, 206, 205, 206, 207, 207, 207, 207, 207, 208, 208,
       208, 208, 208, 208, 208, 208, 209, 209, 210, 210, 210, 211, 210,
       210, 211, 212,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

# Road margin detection using color image

In [13]:
img_copy = np.copy(img)
img_copy.shape

(720, 1280, 3)

In [14]:
img_copy[(img_copy[:, :, 0] < 200) | (img_copy[:, :, 1] < 200) | (img_copy[:, :, 2] < 200)] = 0

cv2.imshow("Color Image", img_copy)

cv2.waitKey(0)
cv2.destroyAllWindows()   # if we want noise than use color image

# sign board detection

In [15]:
img_path = r"C:\Users\photos\desert-1845318_1920.jpg"

img = cv2.imread(img_path)
img = cv2.resize(img, (1280, 720))

img_copy = np.copy(img)

img_copy[(img_copy[:, :, 0] > 50) | (img_copy[:, :, 1] < 150) | (img_copy[:, :, 2] < 150)] = 0  # green or red ko milake yellow bnta h .


img_2 = np.hstack((cv2.resize(img, (650, 500)), cv2.resize(img_copy, (650, 500))))
cv2.imshow("Yellow Road Image", img_2)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Red color pixels extraction

In [17]:
img_path = r"C:\Users\photos\light-trails-659415_1920.jpg"

img = cv2.imread(img_path)
img = cv2.resize(img, (1280, 720))

img_copy = np.copy(img)

img_copy[(img_copy[:, :, 0] > 50) | (img_copy[:, :, 1] > 50) | (img_copy[:, :, 2] < 90)] = 0  # green or red ko milake yellow bnta h .


img_2 = np.hstack((cv2.resize(img, (650, 500)), cv2.resize(img_copy, (650, 500))))
cv2.imshow("color Image vs Color Extracted Image", img_2)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Yellow color pixels extration

In [25]:
img_path = r"C:\Users\photos\street-351481_1920.jpg"

img = cv2.imread(img_path)
img = cv2.resize(img, (1280, 720))

img_copy = np.copy(img)

img_copy[(img_copy[:, :, 0] > 50) | (img_copy[:, :, 1] < 50) | (img_copy[:, :, 2] < 50)] = 0  # green or red ko milake yellow bnta h .


cv2.imshow("Yellow Road Image", img_copy)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Human detection

In [27]:
img_path = r"C:\Users\photos\mother-429158_1920.jpg"

img = cv2.imread(img_path)
img = cv2.resize(img, (1280, 720))

img_copy = np.copy(img)

img_copy[(img_copy[:, :, 0] > 90) | (img_copy[:, :, 1] > 90) | (img_copy[:, :, 2] > 90)] = 255 


img_2 = np.hstack((cv2.resize(img, (650, 500)), cv2.resize(img_copy, (650, 500))))
cv2.imshow("Yellow Road Image", img_2)

cv2.waitKey(0)
cv2.destroyAllWindows()