In [ ]:
# how to access image pixels and modify?

In [1]:
import cv2
import numpy as np

In [8]:
img_path = r"C:\Users\photos\portrait-2865605_1920.jpg"

img = cv2.imread(img_path)
img = cv2.resize(img, (int(img.shape[1]*0.5), int(img.shape[0]*0.5)))
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
img

array([[[218, 227, 230],
        [217, 226, 229],
        [219, 228, 231],
        ...,
        [213, 205, 191],
        [217, 209, 196],
        [222, 215, 202]],

       [[218, 227, 230],
        [219, 228, 231],
        [219, 228, 231],
        ...,
        [214, 206, 192],
        [217, 209, 196],
        [220, 213, 200]],

       [[219, 228, 231],
        [220, 229, 232],
        [219, 228, 231],
        ...,
        [214, 206, 192],
        [218, 210, 197],
        [222, 215, 202]],

       ...,

       [[229, 222, 213],
        [229, 222, 213],
        [229, 222, 213],
        ...,
        [194, 185, 172],
        [193, 184, 171],
        [193, 184, 171]],

       [[228, 221, 212],
        [228, 221, 212],
        [228, 221, 212],
        ...,
        [194, 185, 172],
        [193, 184, 171],
        [192, 183, 170]],

       [[229, 222, 213],
        [228, 221, 212],
        [228, 221, 212],
        ...,
        [193, 184, 171],
        [192, 183, 170],
        [192, 183, 170]]

In [5]:
img.shape

(640, 960, 3)

In [6]:
640* 960     # by this wwe cant count that how many pixels are in this image

614400

In [7]:
img.size

1843200

In [ ]:
# indexing is start from left top of the image
# left to right is x axis horizontallly , top to bottom is y axis.
# 

# access single pixel of image

In [9]:
#   y  x                # by these codes we can get pixels of image
img[0,0]

array([218, 227, 230], dtype=uint8)

In [10]:
img[0,0,0]

218

In [11]:
img[0,0,1]

227

In [12]:
img[0,0,2]

230

In [13]:
img[0][0]

array([218, 227, 230], dtype=uint8)

In [14]:
img[200, 500]

array([151, 162, 204], dtype=uint8)

# show single pixel of image as image

In [16]:
cv2.imshow("image", img[180, 550])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
cv2.imshow("image", img[200, 510])
cv2.waitKey(0)
cv2.destroyAllWindows()

# access the row of image

In [18]:
img[0]

array([[218, 227, 230],
       [217, 226, 229],
       [219, 228, 231],
       ...,
       [213, 205, 191],
       [217, 209, 196],
       [222, 215, 202]], dtype=uint8)

In [19]:
img[0].shape

(960, 3)

In [20]:
img[0, :]       # slicing

array([[218, 227, 230],
       [217, 226, 229],
       [219, 228, 231],
       ...,
       [213, 205, 191],
       [217, 209, 196],
       [222, 215, 202]], dtype=uint8)

# acess the single & double channel image

In [23]:
img[630, :, 1]

array([222, 222, 222, 221, 222, 222, 223, 222, 223, 223, 223, 223, 223,
       223, 223, 224, 224, 224, 224, 223, 223, 224, 223, 221, 221, 219,
       218, 218, 216, 213, 213, 211, 208, 206, 205, 202, 201, 198, 195,
       192, 187, 184, 174, 173, 166, 160, 157, 153, 153, 153, 154, 155,
       153, 154, 155, 156, 158, 158, 157, 157, 155, 157, 158, 158, 157,
       158, 158, 157, 155, 155, 155, 152, 152, 151, 151, 152, 151, 152,
       153, 152, 151, 152, 152, 151, 150, 151, 151, 150, 152, 151, 151,
       152, 153, 152, 152, 153, 153, 152, 152, 152, 152, 153, 153, 153,
       153, 153, 153, 154, 153, 152, 153, 151, 153, 150, 150, 150, 150,
       151, 150, 150, 148, 149, 150, 148, 150, 151, 151, 151, 150, 151,
       151, 152, 152, 154, 153, 153, 152, 152, 153, 152, 154, 153, 153,
       153, 153, 154, 153, 153, 153, 154, 154, 154, 155, 156, 156, 156,
       156, 155, 156, 156, 157, 156, 157, 156, 156, 157, 157, 157, 156,
       158, 159, 161, 163, 166, 169, 172, 174, 178, 179, 181, 18

In [24]:
img[630, :, (0,1)]

array([[228, 228, 228, ..., 196, 196, 197],
       [222, 222, 222, ..., 187, 187, 188]], dtype=uint8)

In [25]:
img[630, :, (2,1,0)]

array([[215, 215, 215, ..., 178, 178, 179],
       [222, 222, 222, ..., 187, 187, 188],
       [228, 228, 228, ..., 196, 196, 197]], dtype=uint8)

In [26]:
cv2.imshow("image", img[:, :,  (2,1,0)])   # 2 is red, 1 is grreen, 0 is blue RGB
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
cv2.imshow("image", img[:, :,  (1,0,2)])   # 1 is gren, 0 is blue, 2 is red GBR
cv2.waitKey(0)
cv2.destroyAllWindows()

# access the column of image

In [29]:
img[:, 700]

array([[195, 195, 195],
       [196, 196, 196],
       [195, 195, 195],
       ...,
       [189, 148,  94],
       [194, 153,  98],
       [193, 152,  97]], dtype=uint8)

In [ ]:
img[:, 300]   # : is rows , 300 is for olumns

# access the column of single & double channel image

In [30]:
img[:, 400, 2]

array([208, 208, 207, 207, 202, 202, 202, 201, 201, 201, 202, 201, 201,
       200, 198, 198, 197, 196, 195, 194, 194, 193, 191, 190, 187, 186,
       185, 182, 180, 179, 177, 176, 174, 172, 171, 170, 170, 171, 168,
       169, 170, 168, 166, 166, 162, 161, 159, 157, 158, 157, 157, 157,
       156, 156, 156, 155, 152, 153, 151, 152, 151, 149, 149, 150, 150,
       150, 150, 150, 149, 148, 148, 144, 146, 142, 142, 141, 140, 139,
       141, 138, 145, 154, 137, 144, 189, 147, 163, 162, 170, 158, 138,
       131, 145, 140, 148, 107, 120,  98,  81,  78,  88, 113, 109,  79,
       133, 136,  96, 115, 145,  90, 131, 112, 126, 143, 154, 102, 168,
       134,  92, 105, 112, 121,  70, 138, 138,  87,  77,  93,  85,  99,
        71,  50, 140, 151,  68, 120,  53,  79,  88, 104, 110,  82, 105,
       161,  92,  65,  87, 139,  49,  73,  89,  56,  66, 111,  73,  63,
        74, 117, 104, 118, 126, 129, 100,  68, 103, 169, 154, 103, 172,
       158, 126, 172, 137,  85, 158, 110,  80, 136, 184, 182, 20

In [32]:
img[:, 200, (1,2)].shape

(640, 2)

# access the part of the image 

In [33]:
img[320:400, 100:600] # syntax is y1:y2, x1:x2# x1 = 100, y1 = 320, x2 = 600, y2 = 400

array([[[189, 195, 200],
        [190, 196, 201],
        [191, 197, 202],
        ...,
        [ 10,  10,  24],
        [ 15,  15,  27],
        [  2,   3,  14]],

       [[188, 194, 199],
        [190, 196, 201],
        [191, 197, 202],
        ...,
        [ 12,  13,  27],
        [ 11,  11,  23],
        [  7,   8,  19]],

       [[187, 193, 198],
        [188, 194, 199],
        [189, 195, 200],
        ...,
        [ 20,  20,  35],
        [  9,   9,  22],
        [  7,   7,  19]],

       ...,

       [[222, 229, 229],
        [216, 227, 226],
        [208, 223, 222],
        ...,
        [ 55,  57,  75],
        [ 22,  22,  38],
        [ 41,  41,  55]],

       [[211, 227, 224],
        [203, 222, 218],
        [196, 217, 211],
        ...,
        [ 45,  48,  67],
        [ 39,  40,  55],
        [ 32,  32,  46]],

       [[198, 220, 215],
        [190, 213, 206],
        [182, 205, 197],
        ...,
        [ 54,  57,  75],
        [ 53,  54,  71],
        [ 29,  29,  43]]

In [34]:
cv2.imshow("image", img[320:400, 100:600])  
cv2.waitKey(0)
cv2.destroyAllWindows()

# show image row wise

In [41]:
for i in range(img.shape[0]):
    cv2.imshow("image", img[0:i+1, :])
    
    if cv2.waitKey(27) & 0xff == ord('q'):
        break
        
cv2.destroyAllWindows()

# show image column wise

In [42]:
for i in range(img.shape[1]):
    cv2.imshow("image", img[:, 0:i+1])
    
    if cv2.waitKey(27) & 0xff == ord('q'):
        break
        
cv2.destroyAllWindows()